version = 1

[project]
name = "888aaa"

[params]
background_hue = 160.0
background_lightness = 0.12
background_saturation = 0.44000006
contrast = 0.85
accent_hue = 205.0
accent_saturation = 0.65
accent_lightness = 0.62
selection_mix = 0.35
vibrancy = 0.813838

[rules.Background]
type = "alias"
source = "bg_0"

[rules.Border]
type = "adjust"
source = "Surface"
op = "Lighten"
amount = 0.08

[rules.Comment]
type = "alias"
source = "TextMuted"

[rules.Cursor]
type = "alias"
source = "fg_2"

[rules.Error]
type = "alias"
source = "accent_0"

[rules.Function]
type = "alias"
source = "accent_5"

[rules.Hint]
type = "alias"
source = "accent_5"

[rules.Info]
type = "alias"
source = "accent_3"

[rules.Keyword]
type = "alias"
source = "accent_4"

[rules.Number]
type = "alias"
source = "accent_2"

[rules.Selection]
type = "mix"
a = "accent_3"
b = "Surface"
ratio = 0.35

[rules.String]
type = "alias"
source = "accent_1"

[rules.Success]
type = "alias"
source = "accent_1"

[rules.Surface]
type = "alias"
source = "bg_1"

[rules.SurfaceAlt]
type = "alias"
source = "bg_2"

[rules.Text]
type = "alias"
source = "fg_1"

[rules.TextMuted]
type = "alias"
source = "fg_0"

[rules.Type]
type = "alias"
source = "accent_3"

[rules.Variable]
type = "alias"
source = "Text"

[rules.Warning]
type = "alias"
source = "accent_2"

[[exports]]
name = "Alacritty"
enabled = true
output_path = "exports/alacritty-theme.toml"

[exports.format]
type = "template"
template_path = "templates/alacritty.toml"

[[exports]]
name = "Template"
enabled = true
output_path = "exports/theme-template.txt"

[exports.format]
type = "template"
template_path = "templates/generic-theme.txt"
